apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: order-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: order
      version: "v1"
  template:
    metadata:
      labels:
        app: order
        version: "v1"
    spec:
      containers:
        - name: order-pod
          image: order:1.0.0
          imagePullPolicy: Never
          ports:
            - name: order-port
              containerPort: 8081
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_DB
            - name: POSTGRES_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: postgres-config 
                  key: POSTGRES_SERVICE

---

apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: "order-port"
  selector:
    app: order
    version: "v1"



